# Generated by Django 5.0.6 on 2024-10-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
